# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./marketplace
    - run: npm run build --if-present
      working-directory: ./marketplace
    - name: AWS ECR
      # You may pin to the exact commit or the version.
      # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
      uses: kciter/aws-ecr-action@v4
      with:
        # The AWS access key id
        access_key_id: AKIAXAYSHCCXOVA7PP62
        # The AWS secret access key
        secret_access_key: ${{ secrets.AWS_SECRET }}
        # AWS Account ID
        account_id: 482685161646
        repo: kdg/marketplace-fe
        # The AWS region
        region: eu-west-1
        tags: latest,${{ github.sha }}
        dockerfile: dockerfile
